version: '2'
services:
    router:
        build: router
        ports:
            - 8080:8080
        links:
            - statsite

    statsite:
        image: alpine
        ports:
            - "8125:8125/udp"
        command: nc -kl 8125

